CREATE TABLE `user` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT ' 自增主键',
  `USER_NAME` varchar(255) NOT NULL COMMENT '账号',
  `PASS_WORD` varchar(255) NOT NULL COMMENT '密码',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_NAME` (`USER_NAME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

